Finance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'assistant'


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('test1.urls')),
    path("", include('assistant.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test1/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
     path("", views.index, name="index"),
     path("exit", views.exit, name="exit"),
     path("panel/", views.panel, name="panel"),
     path('register/', views.register, name="register"),
     path('logear/', views.logear, name='logear'),
     path('reset_password/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset.html"),
          name="reset_password"),
     path('password_reset/done/',
          auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
          name='password_reset_done'),
     path('password_reset_confirm/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
          name='password_reset_confirm'),
     path('reset/done/',
          auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
          name='password_reset_complete'),
     path('eliminar_usuario/<int:user_id>/', views.eliminar_usuario, name='eliminar_usuario'),
     path('nuevo_ingreso/', views.nuevo_ingreso, name="nuevo_ingreso"),
     path('ver_ingreso/', views.ver_ingreso, name="ver_ingreso"),
     path('list_ingreso/', views.list_ingresos, name="list_ingreso"),
     path('borrar_ingreso/<int:id>', views.borrar_ingreso, name="borrar_ingreso"),
     path('editar_ingreso/<int:id>', views.editar_ingreso, name="editar_ingreso"),
     path('nuevo_gasto/', views.nuevo_gasto, name="nuevo_gasto"),
     path('ver_gasto/', views.ver_gastos, name="ver_gasto"),
     path('list_gasto/', views.list_gastos, name="list_gasto"),
     path('borrar_gasto/<int:id>/', views.borrar_gasto, name="borrar_gasto"),
     path('editar_gasto/<int:id>', views.editar_gasto, name="editar_gasto"),
     path('crear_categoria_personalizada/', views.crear_categoria_personalizada, name='crear_categoria_personalizada'),
     path('crear_fuente_personalizada/', views.crear_fuente_personalizada, name='crear_fuente_personalizada'),
     path('ver_perfil/', views.ver_perfil, name="ver_perfil"),
     path('actualizar_imagen/', views.actualizar_imagen, name="actualizar_imagen"),
     path('nueva_deuda/', views.nueva_deuda, name="nueva_deuda"),
     path('list_deuda/', views.list_deudas, name="list_deuda"),
     path('ver_deuda/', views.ver_deudas, name="ver_deuda"),
     path('editar_deuda/<int:id>', views.editar_deuda, name="editar_deuda"),
     path('generar_grafico/', views.generar_grafico, name='generar_grafico'),
     path('nuevo_ahorro/', views.nuevo_ahorro, name='nuevo_ahorro'),
     path('ver_ahorros/', views.ver_ahorros, name='ver_ahorros'),
     path('borrar_ahorro/<int:id>/', views.borrar_ahorro, name="borrar_ahorro"),
     path('editar_ahorro/<int:id>', views.editar_ahorro, name="editar_ahorro"),
     path('list_ahorro/', views.list_ahorro, name="list_ahorro"),
     path('vista_home/', views.vista_home, name="vista_home"),
     


]

test1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import Sum, F, ExpressionWrapper, DecimalField
from decimal import Decimal

class Usuario(AbstractUser):
    email = models.EmailField(max_length=254, unique=True)
    imagen = models.ImageField(upload_to='images', default='images/icon-user.png', null=True, blank=True,)
    # Agrega los atributos 'related_name' en las relaciones
    def __str__(self):
        return str(self.id)

class Cuentas(models.Model):
    saldo = models.DecimalField(max_digits=15, decimal_places=2, blank=False, null=False)
    fk_user = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, blank=True, limit_choices_to={'is_superuser': False})

    def actualizar_saldo(self, monto):
        ingresos = Transacciones.objects.filter(fk_cuenta=self, es_ingreso=True).aggregate(total=Sum('monto'))['total']
        gastos = Transacciones.objects.filter(fk_cuenta=self, es_ingreso=False).aggregate(total=Sum('monto'))['total']
        
        # Utilice expresiones F para actualizar el saldo según el valor anterior
        self.saldo = F('saldo') - ExpressionWrapper(F('saldo') - (ingresos or 0) + (gastos or 0) + monto, output_field=DecimalField())
        self.save()

    def __str__(self):
        return str(self.fk_user)

    def __str__(self):
        return str(self.fk_user)
    
class CategoriaGasto (models.Model):
    nombre_categoria = models.CharField (max_length=50, null=False, blank=False)
    fk_user = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, blank=True, limit_choices_to={'is_superuser': False}, related_name='categorias_personalizadas')


    def __str__(self):
        return self.nombre_categoria

class FuenteIngreso (models.Model):
    nombre_fuente = models.CharField (max_length=50, null=False, blank=False)
    fk_user = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, blank=True, limit_choices_to={'is_superuser': False}, related_name='fuentes_personalizadas')


    def __str__(self):
        return self.nombre_fuente

class Transacciones(models.Model):
    fecha = models.DateField()
    monto = models.DecimalField(max_digits=15, decimal_places=2, blank=False, null=False)
    es_ingreso = models.BooleanField(default=True)
    
    fk_categoria = models.ForeignKey(CategoriaGasto, on_delete=models.CASCADE, null=True, blank=True)
    fk_fuente = models.ForeignKey(FuenteIngreso, on_delete=models.CASCADE, null=True, blank=True)
    fk_cuenta = models.ForeignKey(Cuentas, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        cuenta = self.fk_cuenta
        super(Transacciones, self).save(*args, **kwargs)

        # Obtén los ingresos y gastos actuales de la cuenta
        ingresos = Transacciones.objects.filter(fk_cuenta=cuenta, es_ingreso=True).aggregate(total=Sum('monto'))['total'] or Decimal('0.0')
        gastos = Transacciones.objects.filter(fk_cuenta=cuenta, es_ingreso=False).aggregate(total=Sum('monto'))['total'] or Decimal('0.0')

        # Calcula el saldo de la cuenta
        cuenta.saldo = ingresos - gastos
        cuenta.save()

class Deudas(models.Model):
    descripcion_deuda = models.CharField(max_length=50, null= True, blank= True)
    dia_pago = models.IntegerField(null= True, blank= True)
    valor_total_deuda = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    tipo_de_interes = models.CharField(max_length=50, null=True, blank=True)
    tasa_de_interes_anual = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    tasa_de_interes_mensual = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    plazo_del_prestamo = models.IntegerField(null=True, blank=True)
    valor_interes_mensual = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    fk_user = models.ForeignKey(Usuario, on_delete=models.CASCADE)

    def __str__(self):
        return self.descripcion_deuda
    
class Recordatorio(models.Model):
    fecha = models.DateField()
    mensaje = models.CharField(max_length=255)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    activo = models.BooleanField(default=True)
    deuda = models.ForeignKey(Deudas, on_delete=models.CASCADE, related_name='recordatorios', null=True, blank=True)

    def __str__(self):
        return self.mensaje
    
class Ahorro(models.Model):
    tipo = models.CharField(max_length=50, default="Mi ahorro")
    fecha = models.DateField(null=True)
    monto = models.DecimalField(max_digits=15, decimal_places=2, blank=False, null=False)
    fk_cuenta = models.ForeignKey(Cuentas, on_delete=models.CASCADE)

    def __str__(self):
        return self.tipo
    

test1/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django import forms
from django.forms import ModelForm
from django.forms import DateInput
from decimal import InvalidOperation
#region Usuario
class UsuarioForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['username', 'email', 'password','imagen']
        
class ImageForm(ModelForm):
    class Meta:
        model = Usuario
        fields = ['imagen']

#endregion

#region Ingresos/Gastos       
class IngresosForm(ModelForm):
    class Meta:
        model = Transacciones
        fields = ['fecha', 'monto', 'fk_fuente']
    #   extra_fields = ['']
    #   exclude = ('')
        widgets = {
            'fecha': DateInput(attrs={'type': 'date'}),
            'fk_fuente': forms.Select(attrs={'class': 'form-control w-75 mr-2'}),
            'monto': forms.TextInput(attrs={'class': 'form-control autonumeric'}),
            }

    def clean_fk_fuente(self):
        fuente = self.cleaned_data.get('fk_fuente')
        if not fuente:
            raise forms.ValidationError("Debes seleccionar una fuente.")
        return fuente

class GastosForm(ModelForm):
    class Meta:
        model = Transacciones
        fields = ['fecha', 'monto', 'fk_categoria']
        widgets = {
            'fecha': DateInput(attrs={'type': 'date'}),
            'fk_categoria': forms.Select(attrs={'class': 'form-control w-75 mr-2'}),
            'monto': forms.TextInput(attrs={'class': 'form-control autonumeric'}),
        }

    def clean_fk_categoria(self):
        categoria = self.cleaned_data.get('fk_categoria')
        if not categoria:
            raise forms.ValidationError("Debes seleccionar una categoría.")
        return categoria

#endregion

#region Categoria/Fuente Personalizada
class CategoriaPersonalizadaForm(forms.ModelForm):
    class Meta:
        model = CategoriaGasto
        fields = ['nombre_categoria']
        widgets = {
            'nombre_categoria': forms.TextInput(attrs={'class': 'form-control '}),
        }

class FuentePersonalizadaForm(forms.ModelForm):
    class Meta:
        model = FuenteIngreso
        fields = ['nombre_fuente']
        widgets = {
            'nombre_fuente': forms.TextInput(attrs={'class': 'form-control '}),
        }

#endregion

#region Deudas
TIPOS_DE_INTERES = (
    ('', 'Selecciona un tipo de interés'),
    ('Fijo', 'Interés Fijo'),
    ('Simple', 'Interés Simple'),
)

CAPITALIZACION = (
    ('', 'Selecciona la frecuencia de capitalización'),
    (1, 'Anual'),
    (2, 'Semestral'),
    (4, 'Trimestral'),
    (12, 'Mensual'),
    (365, 'Diaria'),
)

class CustomDecimalInput(forms.widgets.TextInput):
    def __init__(self, attrs=None):
        attrs = {'class': 'form-control', 'type': 'number'} if attrs is None else attrs
        super().__init__(attrs=attrs)

class DeudasForm(forms.ModelForm):
    tasa_de_interes_anual = forms.DecimalField(widget=CustomDecimalInput, required=False)
    tasa_de_interes_mensual = forms.DecimalField(widget=CustomDecimalInput, required=False)
    tipo_de_interes = forms.ChoiceField(choices=TIPOS_DE_INTERES, widget=forms.Select(attrs={'class': 'form-control w-100'}))
    capitalizacion = forms.ChoiceField(choices=CAPITALIZACION, widget=forms.Select(attrs={'class': 'form-control w-100'}), required=False)

    class Meta:
        model = Deudas
        fields = ['descripcion_deuda', 'valor_total_deuda', 'tipo_de_interes', 'tasa_de_interes_anual', 'tasa_de_interes_mensual', 'plazo_del_prestamo', 'capitalizacion', 'dia_pago']
        widgets = {
            'descripcion_deuda': forms.TextInput(attrs={'class': 'form-control w-100'}),
            'dia_pago': forms.TextInput(attrs={'class': 'form-control w-100'}),
            'valor_total_deuda': forms.TextInput(attrs={'class': 'form-control autonumeric'}),
            'tipo_de_interes': forms.TextInput(attrs={'class': 'form-control w-100'}),
            'plazo_del_prestamo': forms.TextInput(attrs={'class': 'form-control w-100'})
        }

    def clean_tasa_de_interes_mensual(self):
        tasa_de_interes_mensual = self.cleaned_data['tasa_de_interes_mensual']
        if tasa_de_interes_mensual is not None:
            return tasa_de_interes_mensual / 100
        else:
            return None
        
    def clean_tasa_de_interes_anual(self):
        tasa_de_interes_anual = self.cleaned_data['tasa_de_interes_anual']
        if tasa_de_interes_anual is not None:
            return tasa_de_interes_anual / 100
        else:
            return None
        
#endregion

class AhorroForm(forms.ModelForm):
    class Meta:
        model = Ahorro
        
        fields = ['fecha', 'monto', 'tipo']

templates/test1/ahorro_home.html
{% extends "layout/base.html" %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %} Graficos {% endblock %}
    <link rel="icon" type="image/jpg" href="{% static 'img/favicon.png' %}" />
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> {% block 'style' %}{% endblock %}
</head>
{% block content %}
{% load humanize %}
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% include 'layout/partials/togler.html' %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->


                {% include 'layout/partials/topnavbar.html' %}

                <div class="col-xl-6 col-lg-6">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h6 class="m-0 font-weight-bold text-success">Deudas</h6>
                        </div>
                        <div class="card-body">
                            {% for ahorro in ahorros %}
                                <h4 class="small font-weight-bold">{{ ahorro.tipo }} - {{ ahorro.tipo }} <span class="float-right">{{ ahorro.tipo }}%</span></h4>
                                <div class="progress mb-4">
                                    <div class="progress-bar" role="progressbar" style="width: {{ ahorro.tipo }}%" aria-valuenow="{{ ahorro.tipo }}" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Copyright &copy; Mi Billetera 2023</span>
                        </div>
                    </div>
                </footer>
            
            
                {% block script %}
                    
            
            
                {% endblock  %} 
                <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
                <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
            
            {% endblock %}

templates/test1/editar_ahorro.html
{% extends 'layout/base.html' %}
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %} Actualizar Ahorro {% endblock %}
    <link rel="icon" type="image/jpg" href="{% static 'img/favicon.png' %}" />
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block 'style' %}{% endblock %}
</head>

{% block content %}
{% load humanize %}

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        {% include 'layout/partials/togler.html' %}
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                {% include 'layout/partials/topnavbar.html' %}
                <!-- Begin Page Content -->
                <div>
                    <div class="container">
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h2 text-success bg-body p-3 mt-2 text-center mx-auto w-50">
                                <b>ACTUALIZAR AHORRO</b>
                            </h1>
                        </div>
                        
                        <form action="{% url 'editar_ahorro' id=id %}" method="POST" class="my form w-75 mx-auto px-5 my-5 shadow-lg"
                            style="border-radius: 10px; padding: 80px 0 80px 0;">

                            
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.fecha.id_for_label }}">Fecha del ahorro:</label>
                                {{ form.fecha }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.tipo.id_for_label }}">Tipo de ahorro:</label>
                                {{ form.tipo }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.monto.id_for_label }}">Monto del ahorro:</label>
                                {{ form.monto }}
                            </div>
                            <button type="submit" class="btn btn-success btn-user btn-block">Actualizar Ahorro</button>
                            {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }} alert alert-success" {% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
{% endblock %}

templates/test1/editar_gastos.html
{% load widget_tweaks %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpg" href="{% static 'img/favicon.png' %}" />
    <title>Mi Billetera | Gastos</title>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        {% include 'layout/partials/togler.html' %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                {% include 'layout/partials/topnavbar.html' %}

                <!-- Begin Page Content -->
                <div>

                    <!-- Page Heading -->
                    <div class="d-flex flex-column w-50 mx-auto">
                        <h1 class="h2 text-success bg-body p-3 mt-5 text-center mx-auto w-50 shadow"><b>ACTUALIZAR GASTO</b></h1>

                        <form action="{% url 'editar_gasto' id=id %}" method="POST" class="my form w-75 mx-auto px-5 my-5 shadow-lg" style="border-radius: 10px; padding: 80px 0 80px 0;">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="{{ form.fecha.id_for_label }}">Fecha del gasto:</label> {{ form.fecha }}
                            </div>
                            <div class="form-group">
                                <label for="{{ form.monto.id_for_label }}">Cantidad o monto del gasto:</label> {{ form.monto }}
                            </div>

                            <div class="form-group ">
                                <label for="{{ form.fk_fuente.id_for_label }}">Categoria del gasto:</label>
                                <div class="d-flex mb-5">
                                    {{ form.fk_categoria }} {% if form.fk_categoria.errors %}
                                    <div class="alert alert-danger">{{ form.fk_categoria.errors }}</div>
                                    {% endif %}
                                </div>

                            </div>

                            <button type="submit" class="btn btn-success btn-user btn-block">Ingresar</button> {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }} alert alert-success" {% endif %}>{{ message }}</li>
                                    {% endfor %}
                            </ul>
                            {% endif %}
                        </form>
                    </div>

                    <script src="https://cdn.jsdelivr.net/npm/autonumeric@4.3.0/dist/autoNumeric.min.js"></script>

                    <script>
                        document.addEventListener("DOMContentLoaded", function() {
                            new AutoNumeric('.autonumeric', {
                                allowDecimalPadding: false,
                                currencySymbol: '',
                                decimalCharacter: ',',
                                digitGroupSeparator: '.',
                                unformatOnSubmit: true
                            });
                        });
                    </script>

                    <script>
                        document.addEventListener("DOMContentLoaded", function() {
                            // Obtén el botón "Guardar" del modal por su ID
                            const guardarCategoriaBtn = document.getElementById("guardarCategoria");

                            // Agrega un evento clic al botón "Guardar"
                            guardarCategoriaBtn.addEventListener("click", function() {
                                console.log("Botón Guardar clickeado");
                                const modalForm = document.getElementById("formCategoriaModal");
                                console.log("Formulario Modal:", modalForm);
                                $.ajax({
                                    url: modalForm.action,
                                    type: "POST",
                                    data: $(modalForm).serialize(),
                                    success: function(response) {
                                        console.log(response);
                                        $("#formularioModal").modal("hide");

                                        // Redireccionar a la URL proporcionada en la respuesta JSON
                                        window.location.href = response.redirect_url;
                                    },
                                    error: function(error) {
                                        // Manejar el error si ocurre
                                        console.error(error);
                                    }
                                });
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
</body>

</html>

templates/test1/nueva_deuda.html
{% load widget_tweaks %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpg" href="{% static 'img/favicon.png' %}" />
    <title>Mi Billetera | Deudas</title>
</head>

<body>

    <body id="page-top">

        <!-- Page Wrapper -->
        <div id="wrapper">

            {% include 'layout/partials/togler.html' %}

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    {% include 'layout/partials/topnavbar.html' %}

                    <!-- Begin Page Content -->
                    <div>

                        <!-- Page Heading -->
                        <div class="d-flex flex-column w-50 mx-auto">
                            <h1 class="h2 text-success bg-body p-3 mt-2 text-center mx-auto w-50 shadow"><b>REGISTRAR DEUDA</b></h1>

                            <form method="POST" class="my form w-75 mx-auto px-5 my-3 shadow-lg" style="border-radius: 10px; padding: 50px 0 50px 0;">
                                {% csrf_token %}

                                <div class="form-group">
                                    {{ form_deuda.descripcion_deuda.label_tag }}
                                    {{ form_deuda.descripcion_deuda }}
                                </div>

                                <div class="form-group">
                                    <label>¿Qué día de cada mes te toca pagar la deuda?:</label>
                                    {{ form_deuda.dia_pago }}
                                </div>

                                <div class="form-group">
                                    <label>Tipo de interés:</label>
                                    {{ form_deuda.tipo_de_interes }}
                                </div>

                                <div class="casilla-interes form-group">
                                    <label>Capitalización:</label>
                                    {{ form_deuda.capitalizacion }}
                                </div>

                                <div class="casilla-interes form-group">
                                    {{ form_deuda.valor_total_deuda.label_tag }}
                                    {{ form_deuda.valor_total_deuda }}
                                </div>

                                <div class="casilla-interes form-group">
                                    <label>Tasa de interés mensual:</label>
                                    {{ form_deuda.tasa_de_interes_mensual }}
                                </div>
                                
                                <div class="casilla-interes form-group">
                                    <label>Tasa de interés anual:</label>
                                    {{ form_deuda.tasa_de_interes_anual }}
                                </div>
                                
                                <div class="casilla-interes form-group">
                                    <label>Plazo del préstamo en meses:</label>
                                    {{ form_deuda.plazo_del_prestamo }}
                                </div>
                            
                                <button type="submit" class="btn btn-success btn-user btn-block mt-3">Ingresar</button>
                            
                                {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }} alert alert-success" {% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </form>
                        </div>

                        <script src="https://cdn.jsdelivr.net/npm/autonumeric@4.3.0/dist/autoNumeric.min.js"></script>

                        <script>
                            document.addEventListener("DOMContentLoaded", function() {
                                new AutoNumeric('.autonumeric', {
                                    allowDecimalPadding: false,
                                    currencySymbol: '',
                                    decimalCharacter: ',',
                                    digitGroupSeparator: '.',
                                    unformatOnSubmit: true
                                });
                            });
                        </script>

                        <script>
                            $(document).ready(function () {
                                // Oculta todas las casillas al cargar la página
                                $('.casilla-interes').hide();
                        
                                // Establece la opción seleccionada en blanco al cargar la página
                                $('#id_tipo_de_interes').val('');

                                // Muestra u oculta las casillas según el tipo de interés seleccionado
                                $('#id_tipo_de_interes').change(function () {
                                    var selectedOption = $(this).val();
                        
                                    // Oculta todas las casillas
                                    $('.casilla-interes').hide();
                        
                                    // Muestra las casillas específicas según el tipo de interés seleccionado
                                    if (selectedOption === 'Fijo') {
                                        $('#id_valor_total_deuda').closest('.casilla-interes').show();
                                        $('#id_tasa_de_interes_mensual').closest('.casilla-interes').show();
                                    } else if (selectedOption === 'Simple') {
                                        $('#id_valor_total_deuda').closest('.casilla-interes').show();
                                        $('#id_tasa_de_interes_anual').closest('.casilla-interes').show();
                                        $('#id_plazo_del_prestamo').closest('.casilla-interes').show();
                                    } else if (selectedOption ==='Compuesto') {
                                        $('#id_capitalizacion').closest('.casilla-interes').show();
                                        $('#id_valor_total_deuda').closest('.casilla-interes').show();
                                        $('#id_tasa_de_interes_anual').closest('.casilla-interes').show();
                                        $('#id_plazo_del_prestamo').closest('.casilla-interes').show();
                                    }
                                });
                                // Hacer el campo requerido
                                $('#id_tipo_de_interes').prop('required', true);
                            });
                        </script>

    </body>

</html>